# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import party.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=party.models.upload_location_other)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('code', models.IntegerField()),
                ('landline', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('capacity', models.IntegerField()),
                ('associated', models.BooleanField(default=True)),
                ('contact_person', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('std_code', models.IntegerField()),
                ('landline', models.IntegerField()),
                ('area', models.CharField(max_length=20)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('zone', models.CharField(max_length=30)),
                ('outside_catering', models.BooleanField(default=False)),
                ('decor', models.BooleanField(default=False)),
                ('no_of_venues', models.IntegerField()),
                ('non_veg', models.BooleanField(default=True)),
                ('extra_details', models.TextField(max_length=500)),
                ('car_parking', models.IntegerField()),
                ('website', models.URLField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('map_link', models.CharField(max_length=300)),
                ('pic', models.ImageField(storage=party.models.OverwriteStorage(), upload_to=party.models.upload_location_main)),
                ('rated_by', models.BigIntegerField()),
                ('avg_rating', models.FloatField()),
                ('cuisines', models.ManyToManyField(to='party.Cuisines')),
                ('rated_user', models.ManyToManyField(to='party.User')),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.User'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Venue'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.User'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Venue'),
        ),
        migrations.AddField(
            model_name='pics',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Venue'),
        ),
    ]
