# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='avg_rating',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='venue',
            name='rated_by',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='rated_user',
            field=models.ManyToManyField(blank=True, to='party.User'),
        ),
    ]
