# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20160329_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='website',
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
