# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20160412_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='map_link',
            field=models.CharField(max_length=3000),
        ),
    ]
